export interface Brand {
  id: string
  label: string
  logo: string
  color: string
}

export const brands: Brand[] = [
  { id: "Toyota", label: "Toyota", logo: "https://cdn.simpleicons.org/toyota", color: "#e60012" },
  { id: "Honda", label: "Honda", logo: "https://cdn.simpleicons.org/honda", color: "#e5202b" },
  { id: "Nissan", label: "Nissan", logo: "https://cdn.simpleicons.org/nissan", color: "#c3002f" },
  { id: "Mitsubishi", label: "Mitsubishi", logo: "https://cdn.simpleicons.org/mitsubishi", color: "#d71920" },
  { id: "Mazda", label: "Mazda", logo: "https://cdn.simpleicons.org/mazda", color: "#101010" },
  { id: "Suzuki", label: "Suzuki", logo: "https://cdn.simpleicons.org/suzuki", color: "#000000" },
  { id: "Daihatsu", label: "Daihatsu", logo: "https://cdn.simpleicons.org/daihatsu", color: "#e2001a" },
  { id: "Subaru", label: "Subaru", logo: "https://cdn.simpleicons.org/subaru", color: "#005c8a" },
  { id: "Isuzu", label: "Isuzu", logo: "https://cdn.simpleicons.org/isuzu", color: "#c41e1e" },
  { id: "Hyundai", label: "Hyundai", logo: "https://cdn.simpleicons.org/hyundai", color: "#002c5f" },
  { id: "Kia", label: "Kia", logo: "https://cdn.simpleicons.org/kia", color: "#bb162b" },
  { id: "Genesis", label: "Genesis", logo: "https://cdn.simpleicons.org/genesis", color: "#000000" },
  { id: "SsangYong", label: "SsangYong", logo: "https://cdn.simpleicons.org/ssangyong", color: "#003366" },
  { id: "BMW", label: "BMW", logo: "https://cdn.simpleicons.org/bmw", color: "#0066b1" },
  { id: "Mercedes", label: "Mercedes", logo: "https://cdn.simpleicons.org/mercedes-benz", color: "#242424" },
  { id: "Audi", label: "Audi", logo: "https://cdn.simpleicons.org/audi", color: "#bb0a30" },
  { id: "Porsche", label: "Porsche", logo: "https://cdn.simpleicons.org/porsche", color: "#000000" },
  { id: "Volkswagen", label: "Volkswagen", logo: "https://cdn.simpleicons.org/volkswagen", color: "#1e50a0" },
  { id: "Opel", label: "Opel", logo: "https://cdn.simpleicons.org/opel", color: "#000000" },
  { id: "Ford", label: "Ford", logo: "https://cdn.simpleicons.org/ford", color: "#003478" },
  { id: "Chevrolet", label: "Chevrolet", logo: "https://cdn.simpleicons.org/chevrolet", color: "#be0000" },
  { id: "GMC", label: "GMC", logo: "https://cdn.simpleicons.org/gmc", color: "#003366" },
  { id: "Cadillac", label: "Cadillac", logo: "https://cdn.simpleicons.org/cadillac", color: "#000000" },
  { id: "Dodge", label: "Dodge", logo: "https://cdn.simpleicons.org/dodge", color: "#333333" },
  { id: "Chrysler", label: "Chrysler", logo: "https://cdn.simpleicons.org/chrysler", color: "#000000" },
  { id: "Jeep", label: "Jeep", logo: "https://cdn.simpleicons.org/jeep", color: "#333333" },
  { id: "Ram", label: "Ram", logo: "https://cdn.simpleicons.org/ram", color: "#000000" },
  { id: "Lincoln", label: "Lincoln", logo: "https://cdn.simpleicons.org/lincoln", color: "#000000" },
  { id: "Buick", label: "Buick", logo: "https://cdn.simpleicons.org/buick", color: "#000000" },
  { id: "Lexus", label: "Lexus", logo: "https://cdn.simpleicons.org/lexus", color: "#113a5f" },
  { id: "Acura", label: "Acura", logo: "https://cdn.simpleicons.org/acura", color: "#000000" },
  { id: "Infiniti", label: "Infiniti", logo: "https://cdn.simpleicons.org/infiniti", color: "#000000" },
  { id: "Peugeot", label: "Peugeot", logo: "https://cdn.simpleicons.org/peugeot", color: "#002e5d" },
  { id: "Renault", label: "Renault", logo: "https://cdn.simpleicons.org/renault", color: "#ffcc00" },
  { id: "Citroen", label: "Citroën", logo: "https://cdn.simpleicons.org/citroen", color: "#003b80" },
  { id: "Fiat", label: "Fiat", logo: "https://cdn.simpleicons.org/fiat", color: "#333333" },
  { id: "Alfa Romeo", label: "Alfa Romeo", logo: "https://cdn.simpleicons.org/alfaromeo", color: "#003399" },
  { id: "Maserati", label: "Maserati", logo: "https://cdn.simpleicons.org/maserati", color: "#000000" },
  { id: "Ferrari", label: "Ferrari", logo: "https://cdn.simpleicons.org/ferrari", color: "#e80a0a" },
  { id: "Lamborghini", label: "Lamborghini", logo: "https://cdn.simpleicons.org/lamborghini", color: "#dab700" },
  { id: "Bentley", label: "Bentley", logo: "https://cdn.simpleicons.org/bentley", color: "#000000" },
  { id: "Rolls-Royce", label: "Rolls-Royce", logo: "https://cdn.simpleicons.org/rollsroyce", color: "#000000" },
  { id: "Aston Martin", label: "Aston Martin", logo: "https://cdn.simpleicons.org/astonmartin", color: "#00594f" },
  { id: "McLaren", label: "McLaren", logo: "https://cdn.simpleicons.org/mclaren", color: "#f58025" },
  { id: "Jaguar", label: "Jaguar", logo: "https://cdn.simpleicons.org/jaguar", color: "#222222" },
  { id: "Land Rover", label: "Land Rover", logo: "https://cdn.simpleicons.org/landrover", color: "#003b26" },
  { id: "Mini", label: "Mini", logo: "https://cdn.simpleicons.org/mini", color: "#000000" },
  { id: "Smart", label: "Smart", logo: "https://cdn.simpleicons.org/smart", color: "#000000" },
  { id: "Tesla", label: "Tesla", logo: "https://cdn.simpleicons.org/tesla", color: "#e71d24" },
  { id: "BYD", label: "BYD", logo: "https://cdn.simpleicons.org/byd", color: "#c41230" },
  { id: "Great Wall", label: "Great Wall", logo: "https://cdn.simpleicons.org/greatwall", color: "#000000" },
  { id: "Geely", label: "Geely", logo: "https://cdn.simpleicons.org/geely", color: "#003366" },
  { id: "Changan", label: "Changan", logo: "https://cdn.simpleicons.org/changan", color: "#003366" },
  { id: "MG", label: "MG", logo: "https://cdn.simpleicons.org/mg", color: "#c41e1e" },
  { id: "Chery", label: "Chery", logo: "https://cdn.simpleicons.org/chery", color: "#c41e1e" },
  { id: "GAC", label: "GAC", logo: "https://cdn.simpleicons.org/gac", color: "#003366" },
]

export const brandModels: Record<string, string[]> = {
  Toyota: ["Camry", "Corolla", "Yaris", "Yaris Cross", "Rav4", "Land Cruiser", "Land Cruiser Prado", "Hilux", "Fortuner", "Avalon", "Supra", "Crown", "Crown Victoria", "Celica", "Starlet", "Tundra", "Tacoma", "4Runner", "Highlander", "Sienna", "Venza", "C-HR", "bZ4X", "GR86", "GR Yaris", "GR Corolla"],
  Honda: ["Civic", "Accord", "CR-V", "HR-V", "BR-V", "Fit/Jazz", "City", "Pilot", "Odyssey", "NSX", "Integra", "Ridgeline", "Passport", "Prelude", "S2000", "Element", "CR-Z", "Insight", "Clarity", "e:Ny1"],
  Nissan: ["Altima", "Sentra", "Maxima", "Patrol", "X-Trail", "Pathfinder", "Kicks", "Sunny", "370Z", "GT-R", "Armada", "Murano", "Rogue", "Qashqai", "Juke", "Frontier", "Titan", "Versa", "Leaf", "Ariya", "Z", "Navara", "Urvan"],
  Mitsubishi: ["Lancer", "Outlander", "Pajero", "Montero", "ASX", "Eclipse Cross", "Mirage", "Triton/L200", "Delica", "Xpander", "Pajero Sport", "Attrage", "i-MiEV"],
  Mazda: ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-30", "CX-5", "CX-50", "CX-60", "CX-70", "CX-8", "CX-9", "CX-90", "MX-5 Miata", "RX-7", "RX-8", "MX-30", "BT-50"],
  Suzuki: ["Swift", "Vitara", "Grand Vitara", "Jimny", "Celerio", "Alto", "Wagon R", "Baleno", "Dzire", "Ertiga", "XL7", "S-Cross", "Ignis", "Kizashi", "Samurai", "Carry"],
  Daihatsu: ["Terios", "Rocky", "Ayla", "Sirion", "Xenia", "Gran Max", "Luxio", "Copen", "Mira", "Move", "Tanto", "Hijet"],
  Subaru: ["Impreza", "WRX", "Outback", "Forester", "Crosstrek", "Legacy", "XV", "Solterra", "Ascent", "BRZ", "Baja", "Tribeca", "Levorg", "WRX STI"],
  Isuzu: ["D-Max", "MU-X", "Trooper", "Rodeo", "Amigo", "VehiCross", "Ascender", "N-Series", "F-Series"],
  Hyundai: ["Elantra/Avante", "Sonata", "Tucson", "Santa Fe", "Kona", "Palisade", "Accent", "i10", "i20", "i30", "Grandeur/Azera", "Creta", "Venue", "IONIQ 5", "IONIQ 6", "Nexo", "Santa Cruz", "Staria", "H-1", "Porter"],
  Kia: ["K5/Optima", "K8", "K9/K900", "Cerato/Forte", "Sorento", "Sportage", "Seltos", "Stinger", "Telluride", "Soul", "Carnival", "Picanto", "Rio", "Ceed", "ProCeed", "EV6", "EV9", "Niro", "Stonic", "Mohave"],
  Genesis: ["G70", "G80", "G90", "GV60", "GV70", "GV80", "Electrified G80"],
  SsangYong: ["Tivoli", "Korando", "Rexton", "Tres", "Musso", "Korando Sports", "Chairman", "Stavic", "Actyon"],
  BMW: ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "i4", "i5", "i7", "iX", "iX1", "iX3", "Z4", "M2", "M3", "M4", "M5", "M8", "XM"],
  Mercedes: ["A-Class", "C-Class", "E-Class", "S-Class", "CLA", "CLS", "GLA", "GLB", "GLC", "GLE", "GLS", "G-Class", "EQA", "EQB", "EQC", "EQE", "EQS", "AMG GT", "Maybach S-Class", "V-Class", "Sprinter"],
  Audi: ["A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "Q8 e-tron", "e-tron GT", "R8", "TT", "RS3", "RS5", "RS6", "RS7", "S3", "S4", "S5", "SQ5"],
  Porsche: ["911", "Cayenne", "Macan", "Panamera", "Taycan", "Boxster", "Cayman", "911 Turbo", "918 Spyder", "Carrera GT"],
  Volkswagen: ["Golf", "Passat", "Tiguan", "Touareg", "Polo", "Jetta", "ID.4", "ID.5", "ID.7", "Arteon", "T-Roc", "T-Cross", "Taos", "Atlas", "Teramont", "Amarok", "Caddy", "Transporter", "Multivan", "Beetle"],
  Opel: ["Corsa", "Astra", "Insignia", "Mokka", "Grandland", "Crossland", "Combo", "Vivaro", "Zafira", "Adam", "Karl", "Meriva"],
  Ford: ["Focus", "Fusion/Mondeo", "Mustang", "Mustang Mach-E", "Explorer", "Escape", "Edge", "F-150", "Ranger", "Bronco", "Expedition", "Ford GT", "Territory", "Endeavour", "Everest", "Transit", "Tourneo", "EcoSport", "Kuga", "Puma", "Maverick"],
  Chevrolet: ["Malibu", "Cruze", "Camaro", "Tahoe", "Suburban", "Silverado", "Traverse", "Equinox", "Trailblazer", "Corvette", "Spark", "Sonic", "Captiva", "Trax", "Blazer", "Bolt", "Colorado", "Express", "Impala", "Lumina"],
  GMC: ["Sierra", "Yukon", "Acadia", "Terrain", "Canyon", "Savana", "Hummer EV"],
  Cadillac: ["CT4", "CT5", "CT6", "Escalade", "XT4", "XT5", "XT6", "Lyriq", "Celestiq", "DeVille", "DTS", "SRX"],
  Dodge: ["Charger", "Challenger", "Durango", "Grand Caravan", "Journey", "Avenger", "Dart", "Viper", "Magnum", "Ram", "Neon"],
  Chrysler: ["300", "Pacifica", "Voyager", "Aspen", "Sebring", "Town & Country", "PT Cruiser", "Crossfire"],
  Jeep: ["Wrangler", "Grand Cherokee", "Cherokee", "Compass", "Renegade", "Gladiator", "Liberty", "Patriot", "Commander", "Wagoneer", "Grand Wagoneer"],
  Ram: ["1500", "2500", "3500", "ProMaster", "ProMaster City", "TRX"],
  Lincoln: ["MKZ", "MKX", "MKT", "MKC", "MKS", "Navigator", "Aviator", "Corsair", "Nautilus", "Continental", "Town Car", "Zephyr"],
  Buick: ["Enclave", "Encore", "Envision", "LaCrosse", "Regal", "LeSabre", "Park Avenue", "Rendezvous", "Terraza", "Verano", "Electra", "Skylark"],
  Lexus: ["ES", "IS", "LS", "LC", "LX", "RX", "NX", "UX", "GX", "TX", "RZ", "LFA", "SC", "HS", "GS", "LM"],
  Acura: ["Integra", "TLX", "MDX", "RDX", "NSX", "ZDX", "RLX", "ILX", "TSX", "CL", "RL", "Legend", "Vigor"],
  Infiniti: ["Q50", "Q60", "QX50", "QX60", "QX80", "QX55", "QX30", "Q70", "QX70", "QX4", "G35", "G37", "M35", "M37", "FX35", "FX37"],
  Peugeot: ["208", "308", "408", "508", "2008", "3008", "5008", "Partner", "Rifter", "Traveller", "Boxer", "Expert", "RCZ", "iOn", "e-208"],
  Renault: ["Clio", "Megane", "Talisman", "Captur", "Kadjar", "Koleos", "Arkana", "Austral", "Zoe", "Twingo", "Scenic", "Espace", "Trafic", "Master", "Kangoo", "Sandero", "Logan", "Duster"],
  Citroen: ["C3", "C4", "C5 X", "C3 Aircross", "C4 Cactus", "C5 Aircross", "Berlingo", "SpaceTourer", "Jumpy", "Jumper", "Ami", "e-C4", "DS3", "DS4", "DS5", "DS7", "DS9"],
  Fiat: ["500", "Panda", "Punto", "Tipo", "Doblo", "Ducato", "Fiorino", "Strada", "Mobi", "Argo", "Cronos", "Torino", "Uno", "Bravo", "Stilo", "Multipla", "Barchetta"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale", "4C", "Giulietta", "MiTo", "Spider", "GTV", "159", "Brera", "GT", "156", "147", "146", "145", "33", "Alfasud"],
  Maserati: ["Ghibli", "Quattroporte", "Levante", "GranTurismo", "GranCabrio", "MC20", "Grecale", "Spyder", "3200 GT", "Coupe"],
  Ferrari: ["F8 Tributo", "SF90 Stradale", "296 GTB", "Roma", "Portofino", "812 Superfast", "LaFerrari", "Enzo", "F40", "F50", "Testarossa", "488 GTB", "458 Italia", "California", "599 GTB", "612 Scaglietti", "575M Maranello", "360 Modena", "F430"],
  Lamborghini: ["Aventador", "Huracán", "Urus", "Revuelto", "Countach", "Diablo", "Murciélago", "Gallardo", "LM002", "Miura", "Espada", "Jalpa", "Silhouette", "Urraco"],
  Bentley: ["Continental GT", "Flying Spur", "Bentayga", "Mulsanne", "Azure", "Brooklands", "Arnage", "Turbo R", "Continental R"],
  "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Dawn", "Cullinan", "Spectre", "Silver Ghost", "Silver Shadow", "Silver Spirit", "Corniche", "Park Ward", "Camargue"],
  "Aston Martin": ["DB11", "DB12", "DBS", "Vantage", "DBX", "Vanquish", "Rapide", "Virage", "DB7", "DB5", "DB9", "One-77", "Valkyrie", "Valhalla", "V12 Zagato"],
  McLaren: ["720S", "750S", "Artura", "Senna", "P1", "Speedtail", "GT", "600LT", "570S", "540C", "MP4-12C", "765LT", "Elva", "Solus GT"],
  Jaguar: ["XE", "XF", "XJ", "XK", "F-Type", "E-Pace", "F-Pace", "I-Pace", "J-Pace", "S-Type", "XJS", "XJR", "X-Type", "C-Type", "D-Type", "E-Type"],
  "Land Rover": ["Range Rover", "Range Rover Sport", "Range Rover Velar", "Range Rover Evoque", "Discovery", "Discovery Sport", "Defender", "Freelander", "LR2", "LR3", "LR4", "Series I", "Series II", "Series III", "Range Rover Classic", "Range Rover LWB"],
  Mini: ["Cooper", "Cooper S", "Clubman", "Countryman", "Convertible", "Coupe", "Roadster", "Paceman", "John Cooper Works", "Electric", "Aceman"],
  Smart: ["Fortwo", "Forfour", "Roadster", "Crossblade", "#1", "#3"],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck", "Roadster", "Semi"],
  BYD: ["Atto 3", "Dolphin", "Seal", "Han", "Tang", "Yuan Plus", "Song Plus", "Qin Plus", "Destroyer 05", "e2", "e3", "D1"],
  "Great Wall": ["Haval H6", "Haval H9", "Haval Jolion", "Haval Dargo", "Haval Shenshou", "Wey Coffee 01", "Wey Mocha", "Ora Good Cat", "Ora Funky Cat", "Tank 300", "Tank 500", "Poer", "Wingle 7"],
  Geely: ["Emgrand", "Monjaro", "Tugella", "Coolray", "Azkarra", "Starray", "Okavango", "Geometry C", "Geometry A", "Icon", "Binrui", "Binyue", "Xingrui", "Xingyue L"],
  Changan: ["CS35", "CS55", "CS75", "CS85", "CS95", "Eado", "UNI-K", "UNI-T", "UNI-V", "Raeton", "Benben", "Lumin", "Shenlan SL03", "Shenlan S7", "Avin"],
  MG: ["MG3", "MG5", "MG6", "MG7", "MG ZS", "MG HS", "MG RX5", "MG Hector", "MG Gloster", "MG Marvel R", "MG4 EV", "MG Cyberster", "MG One"],
  Chery: ["Tiggo 2", "Tiggo 4", "Tiggo 7", "Tiggo 8", "Tiggo 9", "Arrizo 5", "Arrizo 6", "Arrizo 8", "Omoda 5", "Omoda 7", "Omoda C9", "eQ1", "Fulwin", "Cowin", "Karry"],
  GAC: ["GS3", "GS4", "GS5", "GS8", "Emkoo", "Empow", "GN6", "M6", "M8", "Aion S", "Aion Y", "Aion V", "Aion LX", "Trumpchi"],
}
