export interface Country {
  code: string
  nameAr: string
  nameEn: string
  cities: { nameAr: string; nameEn: string }[]
}

export const gulfCountries: Country[] = [
  {
    code: "SA",
    nameAr: "السعودية",
    nameEn: "Saudi Arabia",
    cities: [
      { nameAr: "الرياض", nameEn: "Riyadh" },
      { nameAr: "جدة", nameEn: "Jeddah" },
      { nameAr: "مكة المكرمة", nameEn: "Mecca" },
      { nameAr: "المدينة المنورة", nameEn: "Medina" },
      { nameAr: "الدمام", nameEn: "Dammam" },
      { nameAr: "الخبر", nameEn: "Al Khobar" },
      { nameAr: "الظهران", nameEn: "Dhahran" },
      { nameAr: "الأحساء", nameEn: "Al Ahsa" },
      { nameAr: "الجبيل", nameEn: "Jubail" },
      { nameAr: "حفر الباطن", nameEn: "Hafr Al Batin" },
      { nameAr: "الخرج", nameEn: "Al Kharj" },
      { nameAr: "تبوك", nameEn: "Tabuk" },
      { nameAr: "بريدة", nameEn: "Buraydah" },
      { nameAr: "عنيزة", nameEn: "Unaizah" },
      { nameAr: "الرس", nameEn: "Ar Rass" },
      { nameAr: "حائل", nameEn: "Hail" },
      { nameAr: "نجران", nameEn: "Najran" },
      { nameAr: "جازان", nameEn: "Jazan" },
      { nameAr: "صبيا", nameEn: "Sabya" },
      { nameAr: "أبو عريش", nameEn: "Abu Arish" },
      { nameAr: "الطائف", nameEn: "Taif" },
      { nameAr: "ينبع", nameEn: "Yanbu" },
      { nameAr: "أبها", nameEn: "Abha" },
      { nameAr: "خميس مشيط", nameEn: "Khamis Mushait" },
      { nameAr: "النماص", nameEn: "An Namas" },
      { nameAr: "محايل عسير", nameEn: "Muhayil Aseer" },
      { nameAr: "بيشة", nameEn: "Bisha" },
      { nameAr: "الباحة", nameEn: "Al Bahah" },
      { nameAr: "المندق", nameEn: "Al Mandaq" },
      { nameAr: "المخواة", nameEn: "Al Mikhwah" },
      { nameAr: "القنفذة", nameEn: "Al Qunfudhah" },
      { nameAr: "الليث", nameEn: "Al Lith" },
      { nameAr: "رابغ", nameEn: "Rabigh" },
      { nameAr: "خليص", nameEn: "Khulais" },
      { nameAr: "الكامل", nameEn: "Al Kamil" },
      { nameAr: "تربة", nameEn: "Turubah" },
      { nameAr: "الخرمة", nameEn: "Al Khurmah" },
      { nameAr: "رنية", nameEn: "Ranyah" },
      { nameAr: "عرعر", nameEn: "Arar" },
      { nameAr: "سكاكا", nameEn: "Sakaka" },
      { nameAr: "رفحاء", nameEn: "Rafha" },
      { nameAr: "طريف", nameEn: "Turaif" },
      { nameAr: "عسفان", nameEn: "Asfan" },
      { nameAr: "وادي الدواسر", nameEn: "Wadi Al Dawasir" },
      { nameAr: "الدوادمي", nameEn: "Al Duwadimi" },
      { nameAr: "المجمعة", nameEn: "Al Majma'ah" },
      { nameAr: "الزلفي", nameEn: "Al Zulfi" },
      { nameAr: "شقراء", nameEn: "Shaqra" },
      { nameAr: "عفيف", nameEn: "Afif" },
      { nameAr: "حريملاء", nameEn: "Huraymila" },
      { nameAr: "المزاحمية", nameEn: "Al Muzahmiyya" },
      { nameAr: "ضرماء", nameEn: "Dhurma" },
      { nameAr: "القويعية", nameEn: "Al Quway'iyah" },
      { nameAr: "ثادق", nameEn: "Thadiq" },
      { nameAr: "حرمة", nameEn: "Harmah" },
      { nameAr: "الغاط", nameEn: "Al Ghat" },
      { nameAr: "مرات", nameEn: "Marat" },
      { nameAr: "سراة عبيدة", nameEn: "Sarat Abidah" },
      { nameAr: "ظهران الجنوب", nameEn: "Dhahran Al Janub" },
      { nameAr: "شرورة", nameEn: "Sharurah" },
      { nameAr: "الوجه", nameEn: "Al Wajh" },
      { nameAr: "ضبا", nameEn: "Duba" },
      { nameAr: "أملج", nameEn: "Umluj" },
      { nameAr: "الحناكية", nameEn: "Al Hanakiyah" },
      { nameAr: "بدر", nameEn: "Badr" },
      { nameAr: "تيماء", nameEn: "Tayma" },
      { nameAr: "العلا", nameEn: "Al Ula" },
      { nameAr: "دومة الجندل", nameEn: "Dumat Al Jandal" },
      { nameAr: "بارق", nameEn: "Bariq" },
      { nameAr: "بلقرن", nameEn: "Balqarn" },
      { nameAr: "تنومة", nameEn: "Tanumah" },
      { nameAr: "الدرب", nameEn: "Al Darb" },
      { nameAr: "فرسان", nameEn: "Farasan" },
      { nameAr: "الحوطة", nameEn: "Al Hawtah" },
      { nameAr: "الحريق", nameEn: "Al Hariq" },
      { nameAr: "الدلم", nameEn: "Al Dulaym" },
    ],
  },
  {
    code: "AE",
    nameAr: "الإمارات",
    nameEn: "UAE",
    cities: [
      { nameAr: "دبي", nameEn: "Dubai" },
      { nameAr: "أبو ظبي", nameEn: "Abu Dhabi" },
      { nameAr: "الشارقة", nameEn: "Sharjah" },
      { nameAr: "عجمان", nameEn: "Ajman" },
      { nameAr: "رأس الخيمة", nameEn: "Ras Al Khaimah" },
      { nameAr: "الفجيرة", nameEn: "Fujairah" },
      { nameAr: "أم القيوين", nameEn: "Umm Al Quwain" },
      { nameAr: "العين", nameEn: "Al Ain" },
      { nameAr: "خورفكان", nameEn: "Khor Fakkan" },
      { nameAr: "كلباء", nameEn: "Kalba" },
      { nameAr: "دبا الحصن", nameEn: "Dibba Al Hisn" },
      { nameAr: "دبا الفجيرة", nameEn: "Dibba Al Fujairah" },
      { nameAr: "الذيد", nameEn: "Al Dhaid" },
      { nameAr: "مدينة زايد", nameEn: "Madinat Zayed" },
      { nameAr: "الرويس", nameEn: "Ruwais" },
      { nameAr: "غياثي", nameEn: "Ghayathi" },
      { nameAr: "ليوا", nameEn: "Liwa" },
      { nameAr: "حنيفرية", nameEn: "Haneefriya" },
      { nameAr: "المرر", nameEn: "Al Marar" },
      { nameAr: "مربح", nameEn: "Murabba" },
      { nameAr: "الصجعة", nameEn: "Al Saja'a" },
    ],
  },
  {
    code: "QA",
    nameAr: "قطر",
    nameEn: "Qatar",
    cities: [
      { nameAr: "الدوحة", nameEn: "Doha" },
      { nameAr: "الريان", nameEn: "Al Rayyan" },
      { nameAr: "الوكرة", nameEn: "Al Wakrah" },
      { nameAr: "الخور", nameEn: "Al Khor" },
      { nameAr: "مسيعيد", nameEn: "Mesaieed" },
      { nameAr: "الشمال", nameEn: "Madinat Ash Shamal" },
      { nameAr: "أم صلال", nameEn: "Umm Salal" },
      { nameAr: "الضعاين", nameEn: "Al Da'ayen" },
      { nameAr: "الجميلية", nameEn: "Al Jumayliyah" },
      { nameAr: "الشحانية", nameEn: "Al Shahaniya" },
      { nameAr: "روضة راشد", nameEn: "Rawdat Rashed" },
      { nameAr: "أبو نخلة", nameEn: "Abu Nakhla" },
    ],
  },
  {
    code: "OM",
    nameAr: "عمان",
    nameEn: "Oman",
    cities: [
      { nameAr: "مسقط", nameEn: "Muscat" },
      { nameAr: "صلالة", nameEn: "Salalah" },
      { nameAr: "صحار", nameEn: "Sohar" },
      { nameAr: "السيب", nameEn: "Seeb" },
      { nameAr: "نزوى", nameEn: "Nizwa" },
      { nameAr: "صور", nameEn: "Sur" },
      { nameAr: "عبري", nameEn: "Ibri" },
      { nameAr: "البريمي", nameEn: "Al Buraimi" },
      { nameAr: "إبراء", nameEn: "Ibra" },
      { nameAr: "بلاد بني بو علي", nameEn: "Bilad Bani Bu Ali" },
      { nameAr: "سمائل", nameEn: "Samail" },
      { nameAr: "بهلا", nameEn: "Bahla" },
      { nameAr: "منح", nameEn: "Manah" },
      { nameAr: "أدم", nameEn: "Adam" },
      { nameAr: "الحمراء", nameEn: "Al Hamra" },
      { nameAr: "جعلان بني بو حسن", nameEn: "Jalan Bani Bu Hasan" },
      { nameAr: "جعلان بني بو علي", nameEn: "Jalan Bani Bu Ali" },
      { nameAr: "الكامل والوافي", nameEn: "Al Kamil Wal Wafi" },
      { nameAr: "وادي المعاول", nameEn: "Wadi Al Maawil" },
      { nameAr: "نخل", nameEn: "Nakhal" },
      { nameAr: "العوابي", nameEn: "Al Awabi" },
      { nameAr: "بركاء", nameEn: "Barka" },
      { nameAr: "المصنعة", nameEn: "Al Musanaah" },
      { nameAr: "السويق", nameEn: "Suwaiq" },
      { nameAr: "الخابورة", nameEn: "Al Khaburah" },
      { nameAr: "صحم", nameEn: "Saham" },
      { nameAr: "لوى", nameEn: "Liwa" },
      { nameAr: "شناص", nameEn: "Shinas" },
      { nameAr: "مضحي", nameEn: "Madha" },
      { nameAr: "دبا", nameEn: "Dibba" },
      { nameAr: "خصب", nameEn: "Khasab" },
      { nameAr: "دلك", nameEn: "Dalkut" },
      { nameAr: "مرباط", nameEn: "Mirbat" },
      { nameAr: "طاقة", nameEn: "Taqah" },
      { nameAr: "ثمريت", nameEn: "Thumrait" },
      { nameAr: "هيما", nameEn: "Haima" },
      { nameAr: "محوت", nameEn: "Mahoot" },
      { nameAr: "الدقم", nameEn: "Duqm" },
      { nameAr: "إزكي", nameEn: "Izki" },
      { nameAr: "بدبد", nameEn: "Bidbid" },
      { nameAr: "قريات", nameEn: "Qurayyat" },
    ],
  },
  {
    code: "KW",
    nameAr: "الكويت",
    nameEn: "Kuwait",
    cities: [
      { nameAr: "مدينة الكويت", nameEn: "Kuwait City" },
      { nameAr: "حولي", nameEn: "Hawalli" },
      { nameAr: "الفروانية", nameEn: "Al Farwaniyah" },
      { nameAr: "الأحمدي", nameEn: "Al Ahmadi" },
      { nameAr: "الجهراء", nameEn: "Al Jahra" },
      { nameAr: "مبارك الكبير", nameEn: "Mubarak Al Kabeer" },
      { nameAr: "السالمية", nameEn: "Salmiya" },
      { nameAr: "الرميثية", nameEn: "Rumaithiya" },
      { nameAr: "بيان", nameEn: "Bayan" },
      { nameAr: "السرة", nameEn: "Al Surra" },
      { nameAr: "العديلية", nameEn: "Adailiya" },
      { nameAr: "النزهة", nameEn: "Al Nuzha" },
      { nameAr: "اليرموك", nameEn: "Al Yarmouk" },
      { nameAr: "الشويخ", nameEn: "Shuwaikh" },
      { nameAr: "الزهراء", nameEn: "Al Zahra" },
      { nameAr: "الفردوس", nameEn: "Al Firdous" },
      { nameAr: "الأندلس", nameEn: "Al Andalus" },
      { nameAr: "الرقة", nameEn: "Al Riqqa" },
      { nameAr: "الصباحية", nameEn: "Al Sabahiya" },
      { nameAr: "أبو حليفة", nameEn: "Abu Halifa" },
      { nameAr: "المنقف", nameEn: "Al Mangaf" },
      { nameAr: "الفنطاس", nameEn: "Al Fintas" },
      { nameAr: "المهبولة", nameEn: "Al Mahboula" },
      { nameAr: "الفحيحيل", nameEn: "Al Fahaheel" },
      { nameAr: "الصليبية", nameEn: "Al Sulaibiya" },
      { nameAr: "الشعيبة", nameEn: "Al Shuaybah" },
      { nameAr: "الوفرة", nameEn: "Al Wafra" },
      { nameAr: "دسمان", nameEn: "Dasman" },
      { nameAr: "شرق", nameEn: "Sharq" },
      { nameAr: "المرقاب", nameEn: "Mirqab" },
      { nameAr: "القبلة", nameEn: "Qibla" },
      { nameAr: "الصالحية", nameEn: "Al Salihiya" },
      { nameAr: "المنصورية", nameEn: "Mansouriya" },
      { nameAr: "الضاحية", nameEn: "Al Dhahiya" },
      { nameAr: "قرطبة", nameEn: "Qurtuba" },
      { nameAr: "الخالدية", nameEn: "Al Khalidiyya" },
      { nameAr: "الشامية", nameEn: "Al Shamiya" },
    ],
  },
  {
    code: "BH",
    nameAr: "البحرين",
    nameEn: "Bahrain",
    cities: [
      { nameAr: "المنامة", nameEn: "Manama" },
      { nameAr: "المحرق", nameEn: "Muharraq" },
      { nameAr: "الرفاع", nameEn: "Riffa" },
      { nameAr: "مدينة عيسى", nameEn: "Isa Town" },
      { nameAr: "سترة", nameEn: "Sitra" },
      { nameAr: "الحد", nameEn: "Hidd" },
      { nameAr: "البديع", nameEn: "Budaiya" },
      { nameAr: "الدراز", nameEn: "Duraz" },
      { nameAr: "بني جمرة", nameEn: "Bani Jamra" },
      { nameAr: "جد حفص", nameEn: "Jidhafs" },
      { nameAr: "السنابس", nameEn: "Sanabis" },
      { nameAr: "توبلي", nameEn: "Tubli" },
      { nameAr: "النويدرات", nameEn: "Nuwaidrat" },
      { nameAr: "عالي", nameEn: "Aali" },
      { nameAr: "الزلاق", nameEn: "Zallaq" },
      { nameAr: "جو", nameEn: "Jaww" },
      { nameAr: "كرزكان", nameEn: "Karzakkan" },
      { nameAr: "المالكية", nameEn: "Al Malkiya" },
      { nameAr: "صدد", nameEn: "Sadad" },
      { nameAr: "الشاخورة", nameEn: "Shakhura" },
      { nameAr: "الهملة", nameEn: "Hamala" },
      { nameAr: "دير", nameEn: "Dair" },
      { nameAr: "بسيتين", nameEn: "Busaiteen" },
      { nameAr: "عرفة", nameEn: "Arad" },
      { nameAr: "الحورة", nameEn: "Hoora" },
      { nameAr: "السيف", nameEn: "Al Seef" },
      { nameAr: "الجفير", nameEn: "Juffair" },
    ],
  },
]

export function getCountryByCode(code: string) {
  return gulfCountries.find((c) => c.code === code)
}

export function getCitiesByCountryCode(code: string) {
  const country = getCountryByCode(code)
  return country ? country.cities : []
}
